### ISSUE TITLE
Login on Enter Button press

### ISSUE THREAD

**Issue by meteoDaniel** [RafaelMiquelino/dash-flask-login#6]
Dear Rafael, 

this is a nice project and I have a question to you. 

Do you know how to "login" by pressing the "Enter" Button?

Would be great to receive support from you. 

Best regards

**Comment by RafaelMiquelino** [comment]
Hi,

This feature was not available at the time I created this repository but as this was long ago, it may be available now. You may want to check the Dash oficial docs page at https://dash.plotly.com/. 

If you find the solution, please post it back here as this is a nice feature. 

Thanks

**Comment by RafaelMiquelino** [comment]
@meteoDaniel, Did you find any solution for this?
