### ISSUE TITLE
Elastic Beanstalk

### ISSUE THREAD

**Issue by mikeypatt** [RafaelMiquelino/dash-flask-login#7]
Hi, I would like to upload an app based on your style to elastic beanstalk.

I understand that for that we need two lines
application = app.server

And then:

if __name__ == '__main__':
    application.run_server(debug=True, port=8080)

when I try do this by changing "server = app.server" in serve.py to application and then using the above line it doesn't work. I was wondering if you were able to advise how to go about deploying on AWS Elastic Beanstalk.

Many thanks in advance!

**Comment by mikeypatt** [comment]
It says:
    application.run_server(debug=False, port=8080)
AttributeError: 'Flask' object has no attribute 'run_server'

**Comment by RafaelMiquelino** [comment]
Hi, I don't know the details of AWS Elastic Beanstalk but as this is a service for server less deployment, I would say you have to do something similar than the deployment to Heroku. Take a look at the [Profile](https://github.com/RafaelMiquelino/dash-flask-login/blob/master/Procfile). This is the entry point for Heroku, it may inspire you.
