### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by araichev** [RafaelMiquelino/dash-flask-login#9]
Thanks for making this repo.
I found it helpful and used it to make an alternative public version that suits my needs on [Gitlab](https://gitlab.com/mrcagney/dash_flask_login_example).
If you want to merge my repo into yours that's fine, and just let me know.
Otherwise i'll keep it as a separate repo.

Cheers.

**Comment by RafaelMiquelino** [comment]
Hi, thanks for sharing. If you believe there is a common benefit for other users, feel free to open a PR.

Thanks,
Rafael
